=== AliaksandrLiulis/HumanResourceWebProject/human_resource/src/main/resources/command/commandSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.by.htp.humanresources/command"
	xmlns:tns="http://www.by.htp.humanresources/command">

	<element name="commands">
		<complexType>
			<sequence>
				<element name="command" type="tns:Command" minOccurs="1"
					maxOccurs="unbounded"></element>
			</sequence>
		</complexType>
	</element>

	<complexType name="Command">
		<sequence>
			<element name="key" type="string" />
			<element name="value" type="string" />
		</sequence>
	</complexType>
</schema>

=== AliaksandrLiulis/HumanResourceWebProject/human_resource/src/main/resources/command/commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>
<commands xmlns:tc="http://www.by.htp.humanresources/command"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:schemaLocation="http://www.by.htp.humanresources/command commandSchema.xsd">
	<command>
		<key>cb.login_page</key>
		<value>by.htp.project.human_resource.controller.commandprovider.command.LogInPage</value>
	</command>
	<command>
		<key>cb.registration_page</key>
		<value>by.htp.project.human_resource.controller.commandprovider.command.RegistrationPage</value>
	</command>
	<command>
		<key>cb.main_page</key>
		<value>by.htp.project.human_resource.controller.commandprovider.command.MainPage</value>
	</command>
	<command>
		<key>cb.admin_page</key>
		<value>by.htp.project.human_resource.controller.commandprovider.command.AdminPage</value>
	</command>
	<command>
		<key>cb.hr_page</key>
		<value>by.htp.project.human_resource.controller.commandprovider.command.HrPage</value>
	</command>
	<command>
		<key>cb.boss_page</key>
		<value>by.htp.project.human_resource.controller.commandprovider.command.BossPage</value>
	</command>
	<command>
		<key>cb.employee_page</key>
		<value>by.htp.project.human_resource.controller.commandprovider.command.EmployeePage</value>
	</command>
	<command>
		<key>cb.localization</key>
		<value>by.htp.project.human_resource.controller.commandprovider.command.Localization</value>
	</command>
	<command>
		<key>cb.login_user</key>
		<value>by.htp.project.human_resource.controller.commandprovider.command.LoginUser</value>
	</command>
	<command>
		<key>cb.register_user</key>
		<value>by.htp.project.human_resource.controller.commandprovider.command.RegisterUser</value>
	</command>
	<command>
		<key>cb.expect_page</key>
		<value>by.htp.project.human_resource.controller.commandprovider.command.ExpectPage</value>
	</command>
	<command>
		<key>cb.logout_user</key>
		<value>by.htp.project.human_resource.controller.commandprovider.command.LogOut</value>
	</command>
</commands>
